### ISSUE TITLE
The description of "Timestamp" under "Date Formats" section is not precise?

### ISSUE THREAD

**Issue by shuchu** [DevoInc/python-sdk#154]
In the latest version of https://github.com/DevoInc/python-sdk/blob/master/docs/api/api.md, the description about "Timestamp" is "Millis". In the examples, it is Second. 

Date Formats
Fixed format: As described on Official Python Docs. Accepted formats are:

'%Y-%m-%d %H:%M:%S'
'%Y-%m-%d', the time will be truncated to 00:00:00
Timestamp: From epoch in **millis**

**Comment by angelgcuartero** [comment]
Thank you, we will plan this change to fix it.

**Comment by dvillacanas** [comment]
Thanks for the report, the bug has been fixed and will be uploaded with the next release.

Thank you very much for your feedback.
