### ISSUE TITLE
ModuleNotFoundError: No module named 'parser'

### ISSUE THREAD

**Issue by tannerpalma** [DevoInc/python-sdk#187]
I am experiencing this same error when using the sdk for a query call. I just started using the package today 3/22/2023 so I assume I have the newest version in which this issue was supposed to be fixed (#186) but just wanted to confirm and make aware that this issue is still appearing.

**Comment by JuanFranDevo** [comment]
Please, use version https://github.com/DevoInc/python-sdk/releases/tag/v5.1.2rc2 that corrects the issue. It is still a prerelease version so you can download from https://test.pypi.org/project/devo-sdk/5.1.2rc2/

**Comment by JuanFranDevo** [comment]
Thanks @tannerpalma for your feedback!

Version [5.1.3](https://github.com/DevoInc/python-sdk/releases/tag/v5.1.3) has been released and you can download right now from the standard PyPi repo
