### ISSUE TITLE
DevoSenderException raised by 

### ISSUE THREAD

**Issue by immanuelAtTQ** [DevoInc/python-sdk#289]
Is anyone else getting these errors for a timeout? Could you handle a timeout more gracefully? Note, that we are using v3.6.2, but it appears that the error handling has not changed.

https://github.com/DevoInc/python-sdk/blame/636aa1db27b8798d0aeeddd6f8bd207935aa93f8/devo/sender/lookup.py#L207

While we cannot replicate this issue internally, we have a user showing a 30s timeout resulting in...

```python
TypeError: must be real number, not DevoSenderException
``` 

which is raised by
```python
devo.sender.data.DevoSenderException: Socket error: <class 'OSError'>
````

which is raised by
```python
socket.timeout: The write operation timed out
```

the actual lines that we've been looking at are

https://github.com/DevoInc/python-sdk/blob/v3.6.2/devo/sender/lookup.py
https://github.com/DevoInc/python-sdk/blob/v3.6.2/devo/sender/data.py#L580

**Comment by franjuan** [comment]
Thanks @immanuelAtTQ ! We are already working on it

**Comment by franjuan** [comment]
Please @immanuelAtTQ, can you share with us the whole stack trace of the expeption? We cannot replicate the issue

**Comment by franjuan** [comment]
Sorry, we couldn't reproduce the issue
