### ISSUE TITLE
E-mail event sending with latest version of devo-sdk

### ISSUE THREAD

**Issue by mgananfu** [DevoInc/python-sdk#97]
Hello,

We have a process using devo-sdk that sends events from on-demand-queries via e-mail. This process uses an very old version of devo-sdk. Now, we want to actually inject events on DEVO from that same process so we can configure alarms, but the way we use to use the devo.sender doesn't work with that old version (because we are always using the latest version of devo-sdk).

The question we have is: How to use the e-mail sending function with the latest version of devo-sdk, since it doesn't work with the way it's documented on github.

Thank you.

**Comment by Worvast** [comment]
Hi, the documentation its wrong, we work in upload new version of SDK, soo we fix it too.

Until the update, i put here the correct way for use destination="email":


`
api = Client(auth={"key": "myapikey",
                   "secret": "myapisecret"},
             address="https://apiv2-eu.devo.com/search/query",
             config=ClientConfig(response="json", stream=False, processor=JSON,
                                 destination={
                                     "type": "email",
                                     "params": {
                                         "email.to": "user@devo.com",
                                         "email.subject": "Api v2 Test",
                                         "format": "gzip",
                                     },
                                 }))


response = api.query("from siem.logtrust.web.activity select * limit 10",
                     dates={"from": "yesterday()", "to": "now()"})

`

Any problem warns here, and if it works, then we close the ticket.

**Comment by mgananfu** [comment]
Hi,

We implemented the solution mentioned but we still have problems. When we try to send the data via e-mail we get this error:

`{'error': 'Unable to Start Task: Task Key Duplicate: email_zHRjqNlz3K', 'status': 500, 'timestamp': 1601019417669, 'cid': 'bbe7930a7d63'}`

Any guesses of what can the problem be?

Thanks, greetings.

**Comment by Worvast** [comment]
The customer confirms that they have tried again and it works.

I proceed to close the ticket. If a problem occurs again, do not reopen this, open a new one.

Greetings
